// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.VBox vbox2;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Button button3;
    
    private Gtk.HBox hbox2;
    
    private Gtk.Button button4;
    
    private Gtk.HBox hbox3;
    
    private Gtk.Button button2;
    
    private Gtk.Button button1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar1'/></ui>");
        this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.button3 = new Gtk.Button();
        this.button3.CanFocus = true;
        this.button3.Name = "button3";
        this.button3.UseUnderline = true;
        this.button3.Label = Mono.Unix.Catalog.GetString("Play");
        this.hbox1.Add(this.button3);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.button3]));
        w3.Position = 1;
        w3.Expand = false;
        w3.Fill = false;
        this.vbox2.Add(this.hbox1);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
        w4.Position = 0;
        w4.Expand = false;
        w4.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.button4 = new Gtk.Button();
        this.button4.CanFocus = true;
        this.button4.Name = "button4";
        this.button4.UseUnderline = true;
        this.button4.Label = Mono.Unix.Catalog.GetString("Stop");
        this.hbox2.Add(this.button4);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.button4]));
        w5.Position = 1;
        w5.Expand = false;
        w5.Fill = false;
        this.vbox2.Add(this.hbox2);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.button2 = new Gtk.Button();
        this.button2.CanFocus = true;
        this.button2.Name = "button2";
        this.button2.UseUnderline = true;
        this.button2.Label = Mono.Unix.Catalog.GetString("Connect");
        this.hbox3.Add(this.button2);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox3[this.button2]));
        w7.Position = 0;
        w7.Expand = false;
        w7.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        this.button1.Label = Mono.Unix.Catalog.GetString("Disconnect");
        this.hbox3.Add(this.button1);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox3[this.button1]));
        w8.Position = 2;
        w8.Expand = false;
        w8.Fill = false;
        this.vbox2.Add(this.hbox3);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
        w9.Position = 2;
        w9.Expand = false;
        w9.Fill = false;
        this.vbox1.Add(this.vbox2);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
        w10.Position = 1;
        w10.Expand = false;
        w10.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 400;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.button3.Clicked += new System.EventHandler(this.OnButton3Clicked);
        this.button4.Clicked += new System.EventHandler(this.OnButton4Clicked);
        this.button2.Clicked += new System.EventHandler(this.OnButton2Clicked);
        this.button1.Clicked += new System.EventHandler(this.OnButton1Clicked);
    }
}
